apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: clair-mvrr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clair-mvrr
    app.kubernetes.io/part-of: clair
  name: clair-mvrr
spec:
  ports:
  - port: 6060
    targetPort: 6060
  selector:
    app.kubernetes.io/instance: clair-mvrr
status:
  loadBalancer: {}
