apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: clair-mvrr
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-migration-tenant/clair/clair-mvrr@sha256:6997cde3924b99295b69ccca10e52a1c513d8de25fffe984c3009c9bb04df8d2
        name: container-image
        resources: {}
status: {}
