apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: clair-mvrr
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-migration-tenant/clair/clair-mvrr@sha256:f5787c75bf244103e5ab8186598bb85ab7bb6ba28f053f043fe9cdd7c35ad327
        name: container-image
        resources: {}
status: {}
