apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: clair-mvrr
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-migration-tenant/clair/clair-mvrr@sha256:8b87d125beb534ed0b63780b37653dc037c680ab0211f36a8be07d82a0d22ede
        name: container-image
        resources: {}
status: {}
